# Project information
site_name: 'Ecclesia for MkDocs'
site_description: 'A Material Design theme for MkDocs'
site_author: 'Philippe Logel'
site_url: 'https://github.com/phili67/ecclesiacrm/releases/'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Philippe Logel'

# Configuration
theme:
  name: 'material'
  language: 'fr'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/phili67/ecclesiacrm'
    - type: 'twitter'
      link: 'https://twitter.com/PhilippeLogel'
#    - type: 'linkedin'
#      link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      
# the site map
    
site_name: EcclesiaCRM
pages:
- Accueil: 'index.md'
- Manuel Administrateur:
    - 'Mise en place du CRM': 
        - 'Configuration requise': 'user-guide/doc-installation/doc-requirement.md'
        - "Procédure d'Installation": 'user-guide/doc-installation/doc-install.md'
        - "Localisation CRM en français": 'user-guide/doc-installation/doc-localization.md'
        - "Rapports CRM en français": 'user-guide/doc-installation/doc-report.md'
    - 'Gestion des personnes': 'user-guide/doc-persons.md'
    - 'Gestion des familles': 'user-guide/doc-families.md'
    - 'Gestion des groupes': 'user-guide/doc-groups.md'
    - 'Droits et gestion des utilisateurs du CRM': 
        - "Mise en place d'un utilisateur (administrateur)": 'user-guide/doc-users/doc-users.md'
        - "Gestion des profiles utilisateurs (administrateur)": 'user-guide/doc-users/doc-user-profile.md'
- Manuel utilisateur:
    - "Gérer son profile": 
        - 'Espace Personnel': 'user-guide/doc-user/doc-user-profile.md'
        - 'Réglages personnels': 'user-guide/doc-user/doc-user.md'
    - "calendriers":
        - 'Ajouter supprimer': 'user-guide/doc-user/doc-user-calendar.md'
        - 'Partager son calendrier': 'user-guide/doc-user/doc-user-calendar1.md'
        - 'Partager avec le Mac': 'user-guide/doc-user/doc-user-share-mac.md'
        - 'Créer un événement': 'user-guide/doc-user/doc-user-events.md'
    - "Documents": 
        - 'Gérer-créer': 'user-guide/doc-user/doc-user-document-creation.md'
        - 'Modèles': 'user-guide/doc-user/doc-user-document-templates.md'
        - 'Les partager': 'user-guide/doc-user/doc-user-document-share.md'
    - 'Gestion des fichiers': 
        - 'Introduction': 'user-guide/doc-webdav-file/doc-webdav-intro.md'
        - 'Utiliser la gestion de fichiers sans serveur': 'user-guide/doc-webdav-file/doc-file-use.md'
        - 'Utiliser le serveur de fichiers': 'user-guide/doc-webdav-file/doc-webdav-use.md'
- Manuel du développeur:
    - 'API': 'user-guide/doc-dev/api.md'
- À propos:
    - 'A propos': 'about/about.md'
    - 'Licence': 'about/license.md'
    - 'Notes de mise à jour': 'about/release-notes.md'
