# Project information
site_name: 'Ecclesia for MkDocs'
site_description: 'A Material Design theme for MkDocs'
site_author: 'Philippe Logel'
site_url: 'https://github.com/phili67/ecclesiacrm/releases/'

# Copyright
copyright: 'Copyright &copy; 2017 - 2019 Philippe Logel'

# Configuration
theme:
  name: 'material'
  language: 'fr'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/phili67/ecclesiacrm'
    - type: 'twitter'
      link: 'https://twitter.com/PhilippeLogel'
#    - type: 'linkedin'
#      link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      
# the site map
    
site_name: EcclesiaCRM
pages:
- "Accueil": 'index.md'
- "Manuel : Administrateur":
    - 'Mise en place du CRM': 
        - 'Configuration requise': 'user-guide/doc-installation/doc-requirement.md'
        - "Procédure d'Installation": 'user-guide/doc-installation/doc-install.md'
    - 'Gestion des personnes': 
        - 'Présentation': 'user-guide/doc-admin/person/doc-persons.md'
        - 'Créer une personne': 'user-guide/doc-admin/person/doc-create-person.md'
        - 'Désactiver/supprimer une personne': 'user-guide/doc-admin/person/doc-delete-person.md'
        - 'Personnalisation':
            - 'Gestionnaire de Classification': 'user-guide/doc-admin/person/doc-custom-settings/doc-person-classification.md'
            - 'Liste des propriétés': 'user-guide/doc-admin/person/doc-custom-settings/doc-person-properties.md'
            - 'Champs personnalisables': 'user-guide/doc-admin/person/doc-custom-settings/doc-person-customfields.md'
    - 'Gestion des familles': 
        - 'Présentation': 'user-guide/doc-admin/family/doc-families.md'
        - 'Créer une famille': 'user-guide/doc-admin/family/doc-create-family.md'
        - 'Désactiver supprimer une famille': 'user-guide/doc-admin/family/doc-delete-family.md'
        - 'Personnalisation':
            - 'Rôles de famille': 'user-guide/doc-admin/family/doc-custom-settings/doc-family-roles.md'
            - 'Propriétés de famille': 'user-guide/doc-admin/family/doc-custom-settings/doc-family-properties.md'
            - 'Champs personnalisables de famille': 'user-guide/doc-admin/family/doc-custom-settings/doc-family-customfields.md'
    - 'Gestion des groupes': 
        - 'Présentation': 'user-guide/doc-admin/group/doc-groups.md'
        - 'Création & Menu': 'user-guide/doc-admin/group/doc-groups-management.md'
        - 'Gestion du groupe': 'user-guide/doc-admin/group/doc-groups-managers.md'
        - 'Membres & rôles': 'user-guide/doc-admin/group/doc-groups-members-roles.md'
        - 'Export Contacts': 'user-guide/doc-admin/group/doc-groups-export-contacts.md'
    - 'Droits et gestion des utilisateurs du CRM': 
        - "Mise en place d'un utilisateur (administrateur)": 'user-guide/doc-users/doc-users.md'
        - "Gestion des profiles utilisateurs (administrateur)": 'user-guide/doc-users/doc-user-profile.md'
    - 'Réglages généraux':
        - "Localisation CRM en français": 'user-guide/doc-installation/doc-localization.md'
        - "Rapports CRM en français": 'user-guide/doc-installation/doc-report.md'
        - "Intégration": 'user-guide/doc-admin/doc-settings/doc-settings-integration.md'
#    - 'Personalisation du CRM':

- "Manuel : utilisateur":
    - "Gérer son profile": 
        - 'Espace Personnel': 'user-guide/doc-person/doc-person-profile.md'
        - 'Réglages personnels': 'user-guide/doc-person/doc-person.md'
    - "calendriers":
        - 'Ajouter supprimer': 'user-guide/doc-person/doc-person-calendar.md'
        - 'Partager son calendrier': 'user-guide/doc-person/doc-person-share-calendar.md'
        - 'Partager avec le Mac': 'user-guide/doc-person/doc-person-share-mac.md'
        - 'Créer un événement': 'user-guide/doc-person/doc-person-events.md'
    - "Documents & Modèles": 
        - 'Gérer-créer': 'user-guide/doc-person/doc-person-document-creation.md'
        - 'Les partager': 'user-guide/doc-person/doc-person-document-share.md'
        - 'Modèles de documents': 'user-guide/doc-person/doc-person-document-templates.md'
    - "EDrive dans le CRM": 'user-guide/doc-person/doc-person-document-edrive.md'
    - 'EDrive en dehors du CRM': 
        - 'Introduction': 'user-guide/doc-webdav-file/doc-webdav-intro.md'
        - 'Utiliser le serveur de fichiers': 'user-guide/doc-webdav-file/doc-webdav-use.md'
- "Manuel : pasteur & conseiller":
    - "Suivi Pastoral": 'user-guide/doc-pastoral-care/doc-pastoral-care.md'
    - 'Personnalisation': 
        - "Personnalisation suivi pastoral": 'user-guide/doc-pastoral-care/doc-settings/doc-settings-pastoral-care.md'
- "Campagne de Publipostage":
    - "MailChimp":
        - 'Tableau de bord': 'user-guide/doc-mailchimp/dashboard.md'
        - 'Gérer les listes': 'user-guide/doc-mailchimp/manage_list.md'
        - 'Gérer les campagnes': 'user-guide/doc-mailchimp/manage_campaign.md'
- "Manuel du développeur":
    - 'API': 'user-guide/doc-dev/api.md'
- "À propos":
    - 'A propos': 'about/about.md'
    - 'Licence': 'about/license.md'
    - 'Notes de mise à jour': 'about/release-notes.md'
