# Project information
site_name: 'Ecclesia for MkDocs'
site_description: 'A Material Design theme for MkDocs'
site_author: 'Philippe Logel'
site_url: 'https://github.com/phili67/ecclesiacrm/releases/'

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 Philippe Logel'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
    
# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/phili67/ecclesiacrm'
    - type: 'twitter'
      link: 'https://twitter.com/PhilippeLogel'
#    - type: 'linkedin'
#      link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      
# the site map
    
site_name: EcclesiaCRM
pages:
- Home: 'index.md'
- User Guide:
    - 'Person management': 'user-guide/doc-persons.md'
    - 'Family management': 'user-guide/doc-families.md'
    - 'Groups management': 'user-guide/doc-groups.md'
- Dev Guide:
    - 'API': 'user-guide/doc-dev/api.md'
- About:
    - 'About': 'about/about.md'
    - 'Licence': 'about/license.md'
    - 'Release Notes': 'about/release-notes.md'
